<?php
/**
 * Copyright (C)2015 Mehmet Durgel
 * __main.phtml__
 *
 * @author Mehmet Durgel <md@legrud.net>
 * @date 12-07-2015
 * @time 10:37
 */
?>
<!DOCTYPE html>
<html>
	<head>
		<title><?php echo $data->page['title']; ?></title>
		<meta charset="utf-8">
		<base href="<?php echo $data->baseURL; ?>"/>
		<link rel="stylesheet" type="text/css" href="site.css"/>
		<?php echo utils('asset', array($data)); ?>
	</head>
	<body>
		<div id="page">
			<div id="header" class="container">
				<?php echo render('parts/header' . EXT_PHTML, $data); ?>
			</div>
			<div id="center" class="container">
				<?php echo $data->warnings; ?>
				<?php echo $data->content ?>
			</div>
			<div id="footer" class="container">
				<?php echo render('parts/footer' . EXT_PHTML, $data); ?>
			</div>
		</div>
	</body>
</html>